### 获取token         gateway.factory.dev.efortsh.com/eoth/oauth/token
POST http://gateway.eishare.net/eoth/oauth/token
Authorization: Basic dGVzdDp0ZXN0
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="grant_type"

password
--WebAppBoundary
Content-Disposition: form-data; name="username"

admin
--WebAppBoundary
Content-Disposition: form-data; name="password"

admin1234
--WebAppBoundary--

> {% client.global.set("auth_token",response.body.access_token); %}

###
POST http://gateway.eishare.net/eiam/v1/0/organization/user/user
Authorization: Bearer {{auth_token}}
E-Menu-Id: 50e0ddcfe8fade2d0956bb9a936f58d5
Content-Type: application/json

{"realName":"缪子龙测试","workNo":"2390","cellPhone":"17008305539","departmentId":"","quartersId":"","jobId":"","email":"","userName":"miaozilong","password":"123456","rePassword":"123456"}

###
